FROM node:22-slim AS base

RUN apt-get update && apt-get upgrade -y

RUN apt-get clean && \
    rm -rf /var/cache/apt/archives /var/lib/apt/lists/*

WORKDIR /app

COPY --chown=node:node *.json .
COPY --chown=node:node yarn.lock .
COPY --chown=node:node build.mjs .
COPY --chown=node:node src ./src
COPY --chown=node:node tests ./tests
RUN yarn install && yarn build smoke

FROM grafana/k6:latest
WORKDIR /app
COPY --from=base /app/dist /app