/**
 * Load test — open-workload ramp to answer:
 * "How many simultaneous real users can OpenCRVS handle?"
 *
 * ── Why the previous load test did not answer this question ──────────────────
 *
 * The previous version used ramping-vus with sleep(1) between iterations.
 * Each VU completed a full workflow in ~5–10 s, producing roughly 0.5 req/s of
 * sustained write traffic. A real civil registration worker fills out a form for
 * 60–120 s, reads confirmations, then sits idle before the next case. HTTP calls
 * account for ≈5 % of their session time.
 *
 * Consequence: 100 VUs × ~0.5 req/s ≈ 50 req/s — the load generated by ~1 000
 * real users. The VU count was not the concurrent-user count.
 *
 * ── Open workload model: ramping-arrival-rate ────────────────────────────────
 *
 * Instead of controlling the number of VUs directly (closed model), we control
 * the rate at which new workflow cycles start (open model). k6's
 * ramping-arrival-rate executor allocates exactly the number of VUs needed to
 * sustain the target rate given the observed iteration duration.
 *
 * Because every iteration includes realistic think time (the time the user
 * spends reading, typing, and idling), the VU count at any instant equals the
 * number of concurrent logged-in users. This follows directly from Little's Law:
 *
 *   N = λ × W
 *
 *   N  concurrent users (VUs at any moment)  ← the answer we want
 *   λ  arrival rate (new cycle starts per second)
 *   W  average time one complete user cycle takes, including think time (s)
 *
 * Example: λ = 1 workflow/s, W = 225 s  →  N = 225 concurrent registrars.
 *
 * The test ramps λ from near-zero to MAX_RATE/s in stages and aborts when p95
 * latency sustains above 2 s for 30 s. The peak VU count at that moment is the
 * answer.
 *
 * ── Three user personas ──────────────────────────────────────────────────────
 *
 *   registrar  (50 % of arrivals)
 *     Full create → declare → search → assign → register workflow.
 *     Think time: 60–120 s filling the form, 30–90 s between cases.
 *     Avg cycle: ~3.5 min. Drives the highest per-VU request rate.
 *
 *   searcher   (30 % of arrivals)
 *     Looks up existing records by status, opens one for detail.
 *     Avg cycle: ~2 min. Moderate request rate.
 *
 *   reader     (20 % of arrivals)
 *     Supervisor / admin who glances at the workqueue then does other work.
 *     Avg cycle: ~6 min (mostly idle). Low request rate but HIGH VU count
 *     because the long idle inflates W in Little's Law. This persona dominates
 *     the "logged-in but not actively processing" population.
 *
 * ── Reading the result ───────────────────────────────────────────────────────
 *
 *   The summary prints the peak VU count = peak concurrent real users.
 *
 * Run locally:
 *   yarn test:load
 */

import { check, sleep } from "k6";
import { textSummary } from "https://jslib.k6.io/k6-summary/0.0.2/index.js";
import type { Options } from "k6/options";
import { getSession } from "../src/session";
import {
  assignEvent,
  createEvent,
  declareEvent,
  findUser,
  registerEvent,
  searchByTrackingId,
} from "../src/client";
import { generateDeclaration } from "../src/data";
import { productionThresholds } from "../src/thresholds";

// ─── Configuration ────────────────────────────────────────────────────────────

/**
 * MAX_RATE: peak arrival rate in iterations/second across all scenarios.
 * Each persona's peak rate is derived from this × its weight.
 *
 *   MAX_RATE=2 yarn test:load:cloud   # conservative cloud run
 *   yarn test:load                     # local run, default rate
 */
const MAX_RATE = parseFloat(__ENV.MAX_RATE ?? "5");

/**
 * MAX_VUS: hard ceiling on allocated VUs per scenario.
 * With realistic think times a single iteration can hold a VU for minutes,
 * so this needs to be generous. Little's Law:
 *   registrar: 2.5/s × 210s ≈ 525 VUs
 *   searcher:  1.5/s × 120s ≈ 180 VUs
 *   reader:    1.0/s × 360s ≈ 360 VUs
 */
const MAX_VUS = parseInt(__ENV.MAX_VUS ?? "1200", 10);

// ─── Think time helpers ───────────────────────────────────────────────────────

/** Uniform random between min and max seconds. */
function think(minS: number, maxS: number): void {
  sleep(minS + Math.random() * (maxS - minS));
}

// ─── Arrival-rate stages ──────────────────────────────────────────────────────

/**
 * Ramp stages expressed as fractions of MAX_RATE. Each stage holds long enough
 * for the system to stabilise (Little's Law needs W seconds to reach
 * steady-state VU count).
 */
const RATE_STAGES = [
  { duration: "3m", target: 0.05 }, // warm-up
  { duration: "5m", target: 0.1 },
  { duration: "5m", target: 0.2 },
  { duration: "5m", target: 0.4 },
  { duration: "5m", target: 0.6 },
  { duration: "5m", target: 0.8 },
  { duration: "10m", target: 1.0 }, // peak — hold longer to confirm stability
];

function rateStages(weight: number) {
  return RATE_STAGES.map((s) => ({
    duration: s.duration,
    target: Math.max(1, Math.round(MAX_RATE * s.target * weight)),
  }));
}

// ─── Options ──────────────────────────────────────────────────────────────────

export const options: Options = {
  scenarios: {
    /**
     * 50 % of arrivals — full registration workflow.
     * Avg cycle ≈ 210 s (3.5 min) including think time.
     */
    registrar: {
      executor: "ramping-arrival-rate",
      timeUnit: "1s",
      stages: rateStages(0.5),
      preAllocatedVUs: Math.round(MAX_VUS * 0.45),
      maxVUs: Math.round(MAX_VUS * 0.5),
      exec: "registrarVU",
    },

    /**
     * 30 % of arrivals — search-only workflow.
     * Avg cycle ≈ 120 s (2 min).
     */
    searcher: {
      executor: "ramping-arrival-rate",
      timeUnit: "1s",
      stages: rateStages(0.3),
      preAllocatedVUs: Math.round(MAX_VUS * 0.15),
      maxVUs: Math.round(MAX_VUS * 0.2),
      exec: "searcherVU",
    },

    /**
     * 20 % of arrivals — supervisor glancing at the workqueue.
     * Avg cycle ≈ 360 s (6 min), mostly idle.
     */
    reader: {
      executor: "ramping-arrival-rate",
      timeUnit: "1s",
      stages: rateStages(0.2),
      preAllocatedVUs: Math.round(MAX_VUS * 0.25),
      maxVUs: Math.round(MAX_VUS * 0.3),
      exec: "readerVU",
    },
  },

  thresholds: {
    ...productionThresholds,
    http_req_duration: [
      { threshold: "p(95)<2000", abortOnFail: true, delayAbortEval: "30s" },
    ],
  },
};

// ─── Persona workflows ───────────────────────────────────────────────────────

/**
 * Registrar: full create → declare → search → assign → register cycle.
 * Total think time: ~3–4 min. HTTP time: ~5–10 s.
 */
export function registrarVU(): void {
  const { token, userId } = getSession();

  // Step 1: Create event
  const event = createEvent(token);
  check(event, { "registrar: event created": (e) => Boolean(e?.id) });
  if (!event?.id) return;

  // User fills in the declaration form (60–120 s)
  think(60, 120);

  // Step 2: Declare
  const declaration = generateDeclaration();
  declareEvent(token, event.id, declaration);

  // Wait for ES refresh + user reads confirmation screen (5–15 s)
  think(5, 15);

  // Step 3: Quick search by tracking ID
  const result = searchByTrackingId(token, event.trackingId);
  check(result, { "registrar: search found": (r) => (r?.total ?? 0) > 0 });

  // User reviews search results (10–30 s)
  think(10, 30);

  // Step 4: Assign to self
  assignEvent(token, event.id, userId);

  // User reviews assignment, prepares to register (10–20 s)
  think(10, 20);

  // Step 5: Register
  registerEvent(token, event.id, declaration);

  // Idle between cases — registrar moves to the next case (30–90 s)
  think(30, 90);
}

/**
 * Searcher: looks up records, opens one for detail.
 * Total think time: ~1.5–2.5 min.
 */
export function searcherVU(): void {
  const { token } = getSession();

  // User types a search query (15–30 s)
  think(15, 30);

  // Step 1: Search
  const result = searchByTrackingId(token, ""); // broad search
  check(result, { "searcher: got results": (r) => (r?.total ?? 0) >= 0 });

  // User scans results, picks one (20–40 s)
  think(20, 40);

  // Step 2: Open a specific record (simulated with user lookup)
  const { userId } = getSession();
  findUser(token, userId);

  // User reads the record details (30–60 s)
  think(30, 60);
}

/**
 * Reader: supervisor checks the workqueue, then goes idle.
 * Total think time: ~5–7 min. Only 1–2 HTTP calls.
 */
export function readerVU(): void {
  const { token, userId } = getSession();

  // Step 1: Check workqueue
  findUser(token, userId);

  // Supervisor reads the queue, maybe takes notes (60–120 s)
  think(60, 120);

  // Step 2: Glance at one record
  findUser(token, userId);

  // Goes back to other work — long idle (180–300 s)
  think(180, 300);
}

// ─── Summary ──────────────────────────────────────────────────────────────────

export function handleSummary(data: unknown) {
  return {
    stdout: textSummary(data, { indent: " ", enableColors: false }),
    "summary.json": JSON.stringify(data),
  };
}
