apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "perf-test-generator.fullname" . }}-{{ .Release.Revision }}
  labels:
    app.kubernetes.io/name: {{ include "perf-test-generator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  backoffLimit: {{ .Values.job.backoffLimit }}
  ttlSecondsAfterFinished: {{ .Values.job.ttlSecondsAfterFinished }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "perf-test-generator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: generator
          command:
            - yarn
            - generate-data
            - --count
            - "{{ .Values.env.count }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.command }}
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.args }}
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: EVENTS_POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "perf-test-generator.fullname" . }}-db
                  key: EVENTS_POSTGRES_URL
            - name: BATCH_SIZE
              value: {{ .Values.env.batchSize | quote }}
            - name: SLEEP_MS
              value: {{ .Values.env.sleepMs | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
