apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perf-test-generator.fullname" . }}-db
type: Opaque
stringData:
  EVENTS_POSTGRES_URL: >-
    postgres://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}:{{ .Values.postgres.port }}/{{ .Values.postgres.database }}