apiVersion: v1
kind: Secret
metadata:
  name: {{ include "perf-test-generator.fullname" . }}-db
type: Opaque
data:
  K6_CLOUD_PROJECT_ID: {{ .Values.k6_cloud_project_id | b64enc }}
  K6_CLOUD_TOKEN: {{ .Values.k6_cloud_token | b64enc }}
