image:
  repository: ghcr.io/opencrvs/opencrvs-perf-test
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

job:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

# Optional: override command/args if your image does not already have the right entrypoint
command: []
args: []

env:
  GATEWAY_URL: "http://opencrvs-gateway:3000"

k6_cloud_project_id: ""
k6_cloud_token: ""