name: Build and Push Images

on:
  push:
    branches: ["*"]
    tags: ["*"]

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    name: ${{ matrix.job-name }}
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: opencrvs-data-generator
            dockerfile: Dockerfile.data-generator
          - image_name: opencrvs-perf-test
            dockerfile: Dockerfile.perf-test
    env:
      image_path: ghcr.io/opencrvs/${{ matrix.image_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PUBLISH_TOKEN }}
      - name:
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "image_tag=${TAG_NAME}" >> $GITHUB_ENV
          else
            COMMIT_HASH=$(echo "${GITHUB_SHA}" | cut -c1-7)
            echo "image_tag=${COMMIT_HASH}" >> $GITHUB_ENV
          fi
      - name: Build Docker image
        run: |
          docker build -t ${{ env.image_path }}:${{ env.image_tag }} -f ${{ matrix.dockerfile }} .

      - name: Push Docker image
        run: |
          docker push ${{ env.image_path }}:${{ env.image_tag }}
          docker tag ${{ env.image_path }}:${{ env.image_tag }} ${{ env.image_path }}:latest
          docker push ${{ env.image_path }}:latest
